2017-09-12 18:07:56 WARNING (MainThread) [homeassistant.setup] Setup of notify is taking over 10 seconds.
2017-09-12 18:07:56 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds.
2017-09-12 18:07:57 WARNING (MainThread) [homeassistant.setup] Setup of media_player is taking over 10 seconds.
2017-09-12 18:07:58 WARNING (MainThread) [homeassistant.setup] Setup of device_tracker is taking over 10 seconds.
2017-09-12 18:08:00 WARNING (MainThread) [homeassistant.components.calendar] Setup of platform google is taking over 10 seconds.
2017-09-12 18:08:00 WARNING (MainThread) [homeassistant.components.calendar] Setup of platform google is taking over 10 seconds.
2017-09-12 18:08:00 WARNING (MainThread) [homeassistant.components.calendar] Setup of platform google is taking over 10 seconds.
2017-09-12 18:08:00 WARNING (MainThread) [homeassistant.components.calendar] Setup of platform google is taking over 10 seconds.
2017-09-12 18:08:00 WARNING (MainThread) [homeassistant.components.calendar] Setup of platform google is taking over 10 seconds.
2017-09-12 18:08:17 WARNING (MainThread) [homeassistant.components.sensor.template] Could not render template Thermostat Battery, the state is unknown.
2017-09-12 18:08:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.next_calendar_fb_event fails
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 223, in async_update_ha_state
    yield from self.async_update()
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/sensor/template.py", line 145, in async_update
    self._state = self._template.async_render()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/template.py", line 102, in async_render
    return self._compiled.render(kwargs).strip()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/template.py", line 451, in strptime
    return datetime.strptime(string, fmt)
TypeError: must be str, not None
2017-09-12 18:08:21 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: 
2017-09-12 18:08:44 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/eventManager.cgi?action=getEventIndexes&code=VideoMotion
2017-09-12 18:08:47 WARNING (Thread-5) [homeassistant.components.zwave] zwave not ready after 30 seconds, continuing anyway
2017-09-12 18:08:54 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:09:05 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:09:38 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2017-09-12 18:09:54 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/configManager.cgi?action=getConfig&name=RecordMode
2017-09-12 18:10:03 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSerialNo
2017-09-12 18:10:04 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:10:11 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:10:12 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:10:12 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:10:12 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:10:14 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:10:14 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:10:25 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:11:54 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:12:01 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:12:02 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:12:02 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:12:02 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:12:04 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSerialNo
2017-09-12 18:12:14 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:12:25 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:13:34 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:13:44 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:13:51 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:13:52 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:13:52 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:13:52 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:13:54 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSerialNo
2017-09-12 18:13:54 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:14:04 WARNING (Thread-11) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:14:06 WARNING (Thread-3) [netdisco.ssdp] Found malformed XML at http://192.168.88.18:9080: status=ok
2017-09-12 18:14:15 WARNING (Thread-7) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:15:41 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:15:42 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:15:42 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:15:42 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:15:44 WARNING (Thread-8) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSerialNo
2017-09-12 18:15:44 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/snapshot.cgi?channel=0
2017-09-12 18:15:54 WARNING (Thread-4) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:16:05 WARNING (Thread-5) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:17:34 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/eventManager.cgi?action=getEventIndexes&code=VideoMotion
2017-09-12 18:17:42 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:17:42 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:17:43 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:17:43 WARNING (Thread-10) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:17:44 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:17:55 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:19:24 WARNING (Thread-2) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/eventManager.cgi?action=getEventIndexes&code=VideoMotion
2017-09-12 18:19:32 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:19:33 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:19:33 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:19:33 WARNING (Thread-6) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /cgi-bin/snapshot.cgi?channel=1
2017-09-12 18:19:34 WARNING (Thread-3) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
2017-09-12 18:19:45 WARNING (Thread-12) [requests.packages.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.40.0.11', port=80): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion
